/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts_230441100037_nurmuhammad;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class PilihanFilm extends javax.swing.JFrame {

    String filmTerpilih = "";
    public PilihanFilm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PilihFilm = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DetailFilm = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        Pilih = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        AirMataDiUjungSajadah = new javax.swing.JRadioButton();
        SuzannaMalamJumatKliwon = new javax.swing.JRadioButton();
        SleepCall = new javax.swing.JRadioButton();
        DiAmbangKematian = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        PetualanganSherina2 = new javax.swing.JRadioButton();
        WaktuMaghrib = new javax.swing.JRadioButton();
        Film172Days = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Bioskop Barokah");

        DetailFilm.setBackground(new java.awt.Color(51, 51, 51));
        DetailFilm.setColumns(20);
        DetailFilm.setForeground(new java.awt.Color(255, 255, 255));
        DetailFilm.setRows(5);
        jScrollPane1.setViewportView(DetailFilm);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Detail Film yang anda pilih");

        Pilih.setText("Pilih");
        Pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        PilihFilm.add(AirMataDiUjungSajadah);
        AirMataDiUjungSajadah.setForeground(new java.awt.Color(255, 255, 255));
        AirMataDiUjungSajadah.setText("Air Mata Di Ujung Sajadah");
        AirMataDiUjungSajadah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirMataDiUjungSajadahActionPerformed(evt);
            }
        });

        PilihFilm.add(SuzannaMalamJumatKliwon);
        SuzannaMalamJumatKliwon.setForeground(new java.awt.Color(255, 255, 255));
        SuzannaMalamJumatKliwon.setText("Suzanna: Malam Jumat Kliwon");
        SuzannaMalamJumatKliwon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuzannaMalamJumatKliwonActionPerformed(evt);
            }
        });

        PilihFilm.add(SleepCall);
        SleepCall.setForeground(new java.awt.Color(255, 255, 255));
        SleepCall.setText("SleepCall");
        SleepCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SleepCallActionPerformed(evt);
            }
        });

        PilihFilm.add(DiAmbangKematian);
        DiAmbangKematian.setForeground(new java.awt.Color(255, 255, 255));
        DiAmbangKematian.setText("Di Ambang Kematian");
        DiAmbangKematian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiAmbangKematianActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Daftar Film  saat ini");

        PilihFilm.add(PetualanganSherina2);
        PetualanganSherina2.setText("Petualangan Sherina 2");
        PetualanganSherina2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetualanganSherina2ActionPerformed(evt);
            }
        });

        PilihFilm.add(WaktuMaghrib);
        WaktuMaghrib.setForeground(new java.awt.Color(255, 255, 255));
        WaktuMaghrib.setText("Waktu Maghrib");
        WaktuMaghrib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaktuMaghribActionPerformed(evt);
            }
        });

        PilihFilm.add(Film172Days);
        Film172Days.setForeground(new java.awt.Color(255, 255, 255));
        Film172Days.setText("172 Days");
        Film172Days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Film172DaysActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Film172Days)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaktuMaghrib)
                            .addComponent(PetualanganSherina2)
                            .addComponent(DiAmbangKematian))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SleepCall)
                            .addComponent(SuzannaMalamJumatKliwon)
                            .addComponent(AirMataDiUjungSajadah)))
                    .addComponent(jLabel2))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AirMataDiUjungSajadah, DiAmbangKematian, Film172Days, PetualanganSherina2, SleepCall, SuzannaMalamJumatKliwon, WaktuMaghrib});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(DiAmbangKematian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PetualanganSherina2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WaktuMaghrib))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AirMataDiUjungSajadah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SuzannaMalamJumatKliwon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SleepCall)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Film172Days)
                .addGap(108, 108, 108))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AirMataDiUjungSajadah, DiAmbangKematian, Film172Days, PetualanganSherina2, SleepCall, SuzannaMalamJumatKliwon, WaktuMaghrib});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pilih))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pilih)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiAmbangKematianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiAmbangKematianActionPerformed
        pilihFilm();
    }//GEN-LAST:event_DiAmbangKematianActionPerformed

    private void PetualanganSherina2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetualanganSherina2ActionPerformed
        pilihFilm();
    }//GEN-LAST:event_PetualanganSherina2ActionPerformed

    private void WaktuMaghribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaktuMaghribActionPerformed
        pilihFilm();
    }//GEN-LAST:event_WaktuMaghribActionPerformed

    private void Film172DaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Film172DaysActionPerformed
        pilihFilm();
    }//GEN-LAST:event_Film172DaysActionPerformed

    private void AirMataDiUjungSajadahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirMataDiUjungSajadahActionPerformed
        pilihFilm();
    }//GEN-LAST:event_AirMataDiUjungSajadahActionPerformed

    private void SuzannaMalamJumatKliwonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuzannaMalamJumatKliwonActionPerformed
        pilihFilm();
    }//GEN-LAST:event_SuzannaMalamJumatKliwonActionPerformed

    private void SleepCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SleepCallActionPerformed
        pilihFilm();
    }//GEN-LAST:event_SleepCallActionPerformed

    private void PilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihActionPerformed
        int pilih = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan memesan film" + filmTerpilih + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (pilih == JOptionPane.YES_OPTION) {
            
        }
    }//GEN-LAST:event_PilihActionPerformed

    public void pilihFilm() {
        String detailFilm = "";
        if(DiAmbangKematian.isSelected()) {
            filmTerpilih = "Di Ambang Kematian";
            detailFilm = "Judul Film : Di Ambang Kematian";
        } else if(PetualanganSherina2.isSelected()) {
            filmTerpilih = "Petualangan Sherina 2";
            detailFilm = "Judul Film : Petualangan Sherina 2";
        } else if(WaktuMaghrib.isSelected()) {
            filmTerpilih = "Waktu Maghrib";
            detailFilm = "Judul Film : Waktu Maghrib";
        } else if(Film172Days.isSelected()) {
            filmTerpilih = "172 Days";
            detailFilm = "Judul Film : 172 Days";
        } else if(AirMataDiUjungSajadah.isSelected()) {
            filmTerpilih = "Air Mata Di Ujung Sajadah";
            detailFilm = "Judul Film : Air Mata Di Ujung Sajadah";
        } else if(SuzannaMalamJumatKliwon.isSelected()) {
            filmTerpilih = "Suzanna: Malam Jumat Kliwon";
            detailFilm = "Judul Film : Suzanna: Malam Jumat Kliwon";
        } else if(SleepCall.isSelected()) {
            filmTerpilih = "Sleep Call";
            detailFilm = "Judul Film : Sleep Call";
        } else{
            filmTerpilih = "";
        }
        DetailFilm.setText(detailFilm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihanFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihanFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihanFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihanFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihanFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AirMataDiUjungSajadah;
    private javax.swing.JTextArea DetailFilm;
    private javax.swing.JRadioButton DiAmbangKematian;
    private javax.swing.JRadioButton Film172Days;
    private javax.swing.JRadioButton PetualanganSherina2;
    private javax.swing.JButton Pilih;
    private javax.swing.ButtonGroup PilihFilm;
    private javax.swing.JRadioButton SleepCall;
    private javax.swing.JRadioButton SuzannaMalamJumatKliwon;
    private javax.swing.JRadioButton WaktuMaghrib;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
